### ISSUE TITLE
Panic due to send on already closed eventListener channel (race condition)

### ISSUE THREAD

**Issue by znuh** [DexterLB/mpvipc#5]
I ran into some panics when stopping an EventListener via the stop channel:
```
==================
WARNING: DATA RACE
Write at 0x00c000018550 by goroutine 8:
  runtime.closechan()
      /usr/lib/go-1.13/src/runtime/chan.go:334 +0x0
  github.com/DexterLB/mpvipc.(*Connection).ListenForEvents()
      /.../go/src/github.com/DexterLB/mpvipc/mpvipc.go:142 +0x1bd

Previous read at 0x00c000018550 by goroutine 11:
  runtime.chansend()
      /usr/lib/go-1.13/src/runtime/chan.go:142 +0x0
  github.com/DexterLB/mpvipc.(*Connection).checkEvent.func1()
      /.../go/src/github.com/DexterLB/mpvipc/mpvipc.go:318 +0x5d

Goroutine 8 (running) created at:
  github.com/DexterLB/mpvipc.(*Connection).NewEventListener()
      /.../go/src/github.com/DexterLB/mpvipc/mpvipc.go:153 +0xa5
  main.main()
      /.../projects/gits/private/swdev/go/mpvtest/main.go:42 +0x2df

Goroutine 11 (finished) created at:
  github.com/DexterLB/mpvipc.(*Connection).checkEvent()
      /.../go/src/github.com/DexterLB/mpvipc/mpvipc.go:317 +0x287
  github.com/DexterLB/mpvipc.(*Connection).listen()
      /.../go/src/github.com/DexterLB/mpvipc/mpvipc.go:328 +0x126
==================
panic: send on closed channel

goroutine 372 [running]:
github.com/DexterLB/mpvipc.(*Connection).checkEvent.func1(0xc000019680, 0xc0000e2348)
	/.../go/src/github.com/DexterLB/mpvipc/mpvipc.go:318 +0x5e
created by github.com/DexterLB/mpvipc.(*Connection).checkEvent
	/.../go/src/github.com/DexterLB/mpvipc/mpvipc.go:317 +0x288
```
I attached a short piece of sample code to reproduce the issue: [main.txt](https://github.com/dexterlb/mpvipc/files/10276882/main.txt) (it's a .go file)
This creates and stops an EventListener in quick succession. After a few seconds it should trigger the panic. (Probably depends on video file mpv is playing.)

I think the problem is that the checkEvent function (called from the listen goroutine) can write to the EventListener channel https://github.com/dexterlb/mpvipc/blob/5d27ef06b6c31ac4a35c610f3c95b298a75dbb14/mpvipc.go#L318 after the channel has been closed in the ListenForEvents goroutine https://github.com/dexterlb/mpvipc/blob/5d27ef06b6c31ac4a35c610f3c95b298a75dbb14/mpvipc.go#L142

From what I understand the goroutine for sending data to the EventListener https://github.com/dexterlb/mpvipc/blob/5d27ef06b6c31ac4a35c610f3c95b298a75dbb14/mpvipc.go#L317 is in a race condition against the mutex unlock.

Not sure what's the best way to fix this. One option probably would be one mutex per EventListener. Or postponing the channel close in ListenForEvents and then doing the actual close in checkEvent?

**Comment by znuh** [comment]
I found a solution that works for me and seems reasonable: I replaced the mutex-protected list of `eventListeners` with the Hub pattern used in the gorilla/websocket chat example: [hub.go](https://github.com/gorilla/websocket/blob/master/examples/chat/hub.go).
The Hub receives Events on one channel and distributes them to all not-blocked listener channels. EventListeners are added/removed through register/unregister channels. I made a [fork](https://github.com/znuh/mpvipc/) with this change.

Compared to starting a goroutine for every send to an EventListener one thing is different: If the event-channel used by `ListenForEvents` runs fulll (because the events aren't read fast enough) the Hub can either just drop Events for this listener or it could close the event channel to signal the user instead of silently dropping events.
I decided to simply drop events in case the channel runs full. Additionally I increased the channel capacity in `NewEventListener` to 256.

Let me know if I should create a pull request. The license of the original gorilla hub code is BSD-style so it should be compatible.

**Comment by dexterlb** [comment]
Thank you for your comprehensive work.

I don't see a very straight-forward way of fixing this race without having a "hub" that distributes events to all listeners (what first comes to my head is that each goroutine for sending data to the EventListener could be synchronised with the EventListener, but this will incur an even more significant performance penalty than I imagine creating separate goroutines already does).

So the idea of using `Hub` actually seems like a good compromise, the only downside being the case when the buffer is full.

I think dropping events silently is a bad idea - what I would do is simply remove the `select` and have the slow listener block *all* other listeners that come after it (I realise why they avoided this in gorilla, where latency is critical and workers are usually independent - but I don't imagine there will be such a heterogenous composition of listeners here that would be significantly hampered by a slow listener)

Nevertheless, I also like your idea of having `ListenForEvents` return when the buffer overflows to signal that we've dropped events - if you think it might be useful to never block one listener because another is slow, go ahead and open a PR!

**Comment by znuh** [comment]
You're right, blocking on a slow Listener probably makes the most sense in normal use-cases of mpvipc. I removed the select and made a pull request as you suggested.

**Comment by dexterlb** [comment]
The PR has been merged and this issue is now resolved.
